### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mkovalyk** [yangweigbh/Libgdx-CardBoard-Extension#11]
Hi, 
Thanks for you library. Great work!
I wonder what license do you use? Apache 2.0?
Can I use your library in my commercial project? 
Thanks!

**Comment by intrigus** [comment]
The header of the java files suggests Apache 2.0

**Comment by mkovalyk** [comment]
@intrigus Thanks!
Got used that every library has it's License section in README file.

**Comment by yangweigbh** [comment]
the license should be added in README, thanks
