### ISSUE TITLE
 Can it support both Oculus and Cardboard?

### ISSUE THREAD

**Issue by xeoshow** [yangweigbh/Libgdx-CardBoard-Extension#5]
Hi,

I am new to Libgdx-CardBoard-Extension, looks very promising, can it support both Oculus and Cardboard? 

Thanks!

**Comment by yangweigbh** [comment]
seem to take some time to learn Oculus, i will add that to my schedule:-D

**Comment by xeoshow** [comment]
Great and thanks! Loooks the very promising VR for libgdx!!!
